name: imx8mm-evk
summary: NXP i.MX8M Mini EVK support package
description: |
 Support files for booting i.MX8M Mini EVK board

version: 22-1
type: gadget

base: core22

architectures:
  - build-on: [amd64, arm64]
    build-for: arm64

confinement: strict
grade: stable

parts:
    arm-trusted-firmware:
        plugin: nil
        source: https://github.com/nxp-imx/imx-atf.git
        source-type: git
        source-tag: lf-5.15.32-2.0.0
        source-depth: 1
        override-build: |
            platform="imx8mm"
            make \
                CROSS_COMPILE=${CRAFT_ARCH_TRIPLET}- \
                PLAT=${platform} \
                BUILD_BASE=${CRAFT_PART_BUILD}/build \
                bl31 \
                -j$(nproc)
            make \
                CROSS_COMPILE=${CRAFT_ARCH_TRIPLET}- \
                PLAT=${platform} \
                BUILD_BASE=${CRAFT_PART_BUILD}/build-optee \
                SPD=opteed \
                bl31 \
                -j$(nproc)
            cp ${CRAFT_PART_BUILD}/build/${platform}/release/bl31.bin \
               ${CRAFT_PART_INSTALL}/bl31-${platform}.bin
            cp ${CRAFT_PART_BUILD}/build-optee/${platform}/release/bl31.bin \
               ${CRAFT_PART_INSTALL}/bl31-${platform}.bin-optee
        prime:
            - -*

build-packages:
    - bison
    - build-essential
    - device-tree-compiler
    - flex
    - gcc-aarch64-linux-gnu
    - libxml2-dev
    - libssl-dev
    - python3
    - python3-cryptography
    - python3-pyelftools
    - python3-pycryptodome
    - wget
    - zlib1g-dev
