name: imx8mm-evk
summary: NXP i.MX8M Mini EVK support package
description: |
 Support files for booting i.MX8M Mini EVK board

version: 22-1
type: gadget

base: core22

architectures:
  - build-on: [amd64, arm64]
    build-for: arm64

confinement: strict
grade: stable

parts:
  arm-trusted-firmware:
    plugin: nil
    source: https://github.com/nxp-imx/imx-atf.git
    source-type: git
    source-tag: lf-5.15.71-2.2.0
    source-depth: 1
    override-build: |
      platform="imx8mm"
      make \
        CROSS_COMPILE=${CRAFT_ARCH_TRIPLET}- \
        PLAT=${platform} \
        BUILD_BASE=${CRAFT_PART_BUILD}/build \
        bl31 \
        -j$(nproc)
      make \
        CROSS_COMPILE=${CRAFT_ARCH_TRIPLET}- \
        PLAT=${platform} \
        BUILD_BASE=${CRAFT_PART_BUILD}/build-optee \
        SPD=opteed \
        bl31 \
        -j$(nproc)
      cp ${CRAFT_PART_BUILD}/build/${platform}/release/bl31.bin \
         ${CRAFT_PART_INSTALL}/bl31-${platform}.bin
      cp ${CRAFT_PART_BUILD}/build-optee/${platform}/release/bl31.bin \
         ${CRAFT_PART_INSTALL}/bl31-${platform}.bin-optee
    prime:
      - -*

  optee-keys:
    plugin: dump
    source: https://git.launchpad.net/~ondrak/+git/dev-keys
    source-type: git
    source-branch: ta-keys
    organize:
      '*': ta-keys/
    prime:
      - -*

  optee-os:
    after:
      - optee-fde
      - optee-keys
    plugin: nil
    source: https://github.com/nxp-imx/imx-optee-os.git
    source-type: git
    source-tag: lf-5.15.71-2.2.0
    source-depth: 1
    override-build: |
      export ARCH="arm"
      export CROSS_COMPILE="${CRAFT_ARCH_TRIPLET}-"
      export CROSS_COMPILE_core="${CRAFT_ARCH_TRIPLET}-"
      export CROSS_COMPILE_ta_arm64="${CRAFT_ARCH_TRIPLET}-"
      export CFG_USER_TA_TARGETS="ta_arm64"
      export CFG_ARM64_core=y
      export DEBUG=0
      export CFG_TEE_CORE_LOG_LEVEL=1
      export CFG_TEE_TA_LOG_LEVEL=1
      export CFG_TEE_BENCHMARK=n
      export CFG_TEE_RAM_VA_SIZE=0x00280000
      export CFG_CORE_HEAP_SIZE=0x00100000
      # set NXP platform
      export PLATFORM=imx
      export PLATFORM_FLAVOR=mx8mmevk
      # add optee-fde TA
      cp -r ${CRAFT_STAGE}/optee-fde/ta/fde_key_handler ${CRAFT_PART_BUILD}/ta/
      # determine keys to be used
      export TA_PUBLIC_KEY="${CRAFT_STAGE}/ta-keys/ta_public.pem"
      make O=${CRAFT_PART_BUILD}/out -j$(nproc)
      make O=${CRAFT_PART_BUILD}/out -j$(nproc) \
         CFG_EARLY_TA=y \
         EARLY_TA_PATHS="out/ta/pkcs11/fd02c9da-306c-48c7-a49c-bbd827ae86ee.stripped.elf \
                 out/ta/trusted_keys/f04a0fe7-1f5d-4b9b-abf7-619b85b4ce8c.stripped.elf \
                 out/ta/fde_key_handler/fd1b2a86-3668-11eb-adc1-0242ac120002.stripped.elf"
      ${CRAFT_ARCH_TRIPLET}-objcopy \
         -O binary \
         ${CRAFT_PART_BUILD}/out/core/tee.elf \
         ${CRAFT_PART_INSTALL}/tee.bin
    prime:
      - -*

  optee-fde:
    plugin: dump
    source: https://git.launchpad.net/~ondrak/+git/optee-uc-fde
    source-type: git
    source-branch: master
    override-pull: |
      craftctl default
      git apply ${CRAFT_PROJECT_DIR}/0001-ta-disable-TA-lock.patch
    organize:
      '*': optee-fde/
    prime:
      - -*

build-packages:
  - bison
  - build-essential
  - device-tree-compiler
  - flex
  - libxml2-dev
  - libssl-dev
  - python3
  - python3-cryptography
  - python3-pyelftools
  - python3-pycryptodome
  - wget
  - zlib1g-dev
  - on amd64:
    - gcc-aarch64-linux-gnu
  - on arm64:
    - gcc
